name: Update news.mp3 and Create Release

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest news.mp3
        run: |
          curl -s -o news.mp3 https://webservice.westfunk.de/audiodata/rabo/news.mp3

      - name: Calculate hash of downloaded file
        id: hash
        run: |
          sha256sum news.mp3 | awk '{print $1}' > new_hash.txt

      - name: Compare with previous hash
        id: changed
        run: |
          if [ -f .last_hash.txt ]; then
            if cmp -s .last_hash.txt new_hash.txt; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push updated news.mp3 and hash
        if: steps.changed.outputs.changed == 'true'
        run: |
          mv new_hash.txt .last_hash.txt
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add news.mp3 .last_hash.txt
          git commit -m "Update news.mp3 with latest version"
          git push

      - name: Create GitHub Release with news.mp3
        if: steps.changed.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d_%H-%M-%S")
          TAG="news-$TIMESTAMP"
          gh release create "$TAG" \
            --title "News Update $TIMESTAMP" \
            --notes "Automated news.mp3 update" \
            news.mp3
